

#SRC_USERMOD_C += $(SCREENBUF_MOD_DIR)/screenbuf.c


SCREENBUF_MOD_DIR := $(USERMOD_DIR)
SRC_USERMOD += $(addprefix $(SCREENBUF_MOD_DIR)/, screenbuf.c)
CFLAGS_USERMOD += \
	-I$SCREENBUF_MOD_DIR \
        -DMODULE_SCREENBUF_ENABLED=1
